export class EmployeeModel{
empId:number;
name:string;
city:string;
state:string;
emailId:string;
mobileNo:string;
pinCode:string
address:string;
constructor(){
    this.empId=1;
    this.name='';
    this.city='';
    this.state='';
    this.emailId='';
    this.mobileNo='';
    this.address='';
    this.pinCode=''
}
}